### ISSUE TITLE
安装后，vscode命令框中，输入 LeetCode C++ Debugger: Start Debugging 无法找到

### ISSUE THREAD

**Issue by HanWangyang** [XavierCai1996/vscode-leetcode-cpp-debug#1]
Hi ，如题
![2020-04-20_10-43-30](https://user-images.githubusercontent.com/28434250/79709078-d2970d80-82f3-11ea-9446-3e70558e1536.jpg)

**Comment by XavierCai1996** [comment]
这种情况可能是插件的初始化失败导致对应命令未能挂载成功，请问是否在启动VS Code的过程中看到错误提示框？

**Comment by XavierCai1996** [comment]
突然发现一个低级错误，命令实际为`LeetCode Debugger: Start Debugging`，在README文档中的描述是错误的（现已更新），您可以看看您是否是因为这个问题而找不到命令。

**Comment by HanWangyang** [comment]
原来是这个命令，我重新试下，多谢~~
