### ISSUE TITLE
Failed to start debugging: Error: Can not find entry function in class [Solution].

### ISSUE THREAD

**Issue by CorsicaL** [XavierCai1996/vscode-leetcode-cpp-debug#19]
版本：
macOS Big Sur 11.6
vscode 1.16.2

执行插件debug的时候报错
> Failed to start debugging: Error: Can not find entry function in class [Solution].

插件设置中

```json
"leetcode-cpp-debugger.deleteTemporaryContents": false
"leetcode-cpp-debugger.source": "[online]leetcode-cn.com"
```

debug的时候fetch problem后没有下载leetcode-main.cpp和其他一系列头文件

无法debug的leetcode-cn题号为31，但该题可以正常通过leetcode插件提交并ac

与此同时，在debug本地另一道题（题号17）的时候不会出现这个问题

**Comment by xavier-cai** [comment]
看起来是因为这个问题的返回值是void，和其他问题的输出方式不一样，估计得修一下了...

**Comment by xavier-cai** [comment]
已于 ddabcffff6d2cb5a7acf351add4503c0d577bc73 (v0.0.9) 修复
