### ISSUE TITLE
无法打开“leetcode-handler.h”

### ISSUE THREAD

**Issue by halo-geng** [XavierCai1996/vscode-leetcode-cpp-debug#20]
显示无法打开“leetcode-handler.h”，请问leetcode-entry.h中引用的头文件leetcode-handler.h在什么位置呢

**Comment by xavier-cai** [comment]
Hi，handler文件是根据当前用户的solution自动生成的代码文件，对应的生成代码：[code](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/blob/master/src/debuggers/cppDebugger.ts#L29)

**Comment by xavier-cai** [comment]
请问找不到handler是正常用户使用中出现的问题，还是其他情况下出现的问题呢？

**Comment by halo-geng** [comment]
您好，是正常用户使用中出现的问题，使用LeetCode Debugger: Start Debugging启动调试后就会出现这一问题

**Comment by halo-geng** [comment]
问题已解决，感谢！

leetcode-handler.h:6:10: fatal error: 2.两数相加.cpp: No such file or directory
 #include "2.两数相加.cpp"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

原因如上，cpp文件是通过leetcode插件自动生成的，文件名中包含中文，改为英文即可
