### ISSUE TITLE
当文件为中文名的时候会报错

### ISSUE THREAD

**Issue by Mao-Hao** [XavierCai1996/vscode-leetcode-cpp-debug#22]
cpp生成代码的时候，如果当前文件的名字包含中文，会生成#inlcude<中文名>这样的错误代码。

**Comment by xavier-cai** [comment]
抱歉回复迟了，你有试过[Output File Encoding](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/blob/master/README_zh-CN.md#%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE)这个设置吗？

**Comment by Mao-Hao** [comment]
不好意思我之前没看仔细误会了，以为gbk不仅仅是临时文件的编码。
切成gbk后一切正常，谢谢您 ;)
