### ISSUE TITLE
unspport file type

### ISSUE THREAD

**Issue by IiMM0811** [XavierCai1996/vscode-leetcode-cpp-debug#29]
c语言，右下角提示：
![image](https://user-images.githubusercontent.com/61083617/222971006-dfb94d9d-1ff0-4f87-b9b2-9228b5643d11.png)

**Comment by xavier-cai** [comment]
截图这个问题是因为目前只认cpp作为合法的文件后缀。

不过插件需要c++环境，纯c语言环境应该是缺库的。
