### ISSUE TITLE
运行后会出现这种情况，已被删除

### ISSUE THREAD

**Issue by yangninghua** [XavierCai1996/vscode-leetcode-cpp-debug#3]
![image](https://user-images.githubusercontent.com/32252319/79939538-f98b4600-8491-11ea-9223-945a334e31c1.png)

**Comment by XavierCai1996** [comment]
这是正常的设定，`leetcode-main.cpp`属于临时的代码文件，用于在编译时提供入口的`main`函数，而在调试结束后则会被删除。

如果您想保留临时文件，可以在退出调试前在工作目录复制这些文件。
