### ISSUE TITLE
Debug no response

### ISSUE THREAD

**Issue by chagelo** [XavierCai1996/vscode-leetcode-cpp-debug#33]
When press ctrl+shift+p, select `LeetCode Debugger: Start Debugging` and run, no reaction. It does not generate any files in current directory, I have set `delete temporay files` to false.

**Comment by xavier-cai** [comment]
Hi, could you share more context like what's your C++ dev env, and what code you was running the debug tool.

**Comment by chagelo** [comment]
Sorry for replying so late.
I use this extension in windows11, my compiler is mingw g++, my code is just an empty leetcode problem.
![image](https://github.com/user-attachments/assets/091c294a-e0a2-483e-a0c7-3522c2fb1af6)

**Comment by xavier-cai** [comment]
I tried this in my local env (followed [this](https://code.visualstudio.com/docs/cpp/config-mingw) to set up mingw g++), it works well for me.

You can try below steps:
1. Make sure your local C++ env works: manually add main function into this leetcode problem file and debug/run it. If it works, then go next step.
2. Run LeetCode debugger plugin with temporary file: I see your workspace already having these temporary files (though you mentioned "not generate any files"), you can go to "leetcode-main.cpp" which having the main function and debug/run it.

**Comment by xavier-cai** [comment]
Also, one more possible issue is the you may need to add `return 0;` to function `maxSumDivThree`.

**Comment by chagelo** [comment]
> Sorry for replying so late. I use this extension in windows11, my compiler is mingw g++, my code is just an empty leetcode problem. ![image](https://private-user-images.githubusercontent.com/49865033/372763775-091c294a-e0a2-483e-a0c7-3522c2fb1af6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjk1NzMsIm5iZiI6MTcyODI2OTI3MywicGF0aCI6Ii80OTg2NTAzMy8zNzI3NjM3NzUtMDkxYzI5NGEtZTBhMi00ODNlLWEwYzctMzUyMmMyZmIxYWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAyNDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZjA4YmQ0MTBiOTJmYTE2NTI5NTc3MzM4M2IwNjIyOTdmYTViNjNjNGY2MGFhZWIyMDRhOTRjZTY5YWE5YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7g_rhnmnd99suS38O8EIVGTwIKYXZF1DxC98UzjKLA4)

1. Soryy, I repeat the steps in my newly created wsl, but it seems not work. In my root path, the template files are not generated when I `ctrl+shift+p`.
2. After I delete the template files in my envrioments showed int the above image, I `ctrl+shift+p` it does not work.
3. After I add main and head files, it can indeed be debugged.
4. There might be some matter with my local environment. Later I will try in my another laptop.


![image](https://github.com/user-attachments/assets/88f9e259-c8d2-4c21-8b17-0c21edade3e7)

**Comment by xavier-cai** [comment]
It's a little bit confusing me on if the temporary files can be generated or not. Correct me if my understanding is wrong:
1. You have 2 envs
    1. The first env is in Windows with mingw (shown as 1st pic), it **CAN** generate temporary files but can **NOT** start the debugging process
        1. Here is my comment: since it already generating temporary files, could you try to manully add `#include "leetcode-definition.h"` to your `1262.可被3整除的最大和.cpp` and then start VSCode debugging on `leetcode-main.cpp` as it containing `main` function so that we can know if the VSCode debugging is not working or the debugger can not trigger the VSCode debugging process.
    1. The second env is in WSL (show as 2nd pic), it can **NOT** generate temporary file
        1. Here is my comment: since it can not generate temporary file, there usually having some error message when you starting the debugger via `ctrl+shift+P`, could you share the error message if possible. A possible reason is that the file name like `1.两数之和` is containing Chinese characters, you can try to set the value of conifg[Output File Encoding](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/blob/master/README_zh-CN.md#%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE) to "gbk".

**Comment by chagelo** [comment]
Both has no temporary files generated.

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/e9f17f68-2a99-44fc-a102-4d6b22b544e6">

**Comment by chagelo** [comment]
Have the same `Fetch problem failed: Request connect error.` in my another pc, Ubuntu 22.04, I just tried several minutes ago.

**Comment by xavier-cai** [comment]
It means you have network issue, have you checked the config [`Source`](https://github.com/xavier-cai/vscode-leetcode-cpp-debug/blob/master/README_zh-CN.md#%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE)? Try to switch it to CN leetcode endpoint or just use local.

**Comment by chagelo** [comment]
Ok, it works well after I switch the `Source` to local. 😂

Thank you for your help.
