### ISSUE TITLE
Fetch problem failed: Request connect error.

### ISSUE THREAD

**Issue by XiaoJiNu** [XavierCai1996/vscode-leetcode-cpp-debug#4]
您好，请问我执行“通过在命令输入板(Ctrl/Cmd + Shift + P)输入命令LeetCode Debugger: Start Debugging来启动.” 这一步后出现下面错误：
Fetch problem failed: Request connect error.请教这是什么错误？
我安装的扩展如下
![图片](https://user-images.githubusercontent.com/30587645/81565212-9410e200-93cb-11ea-939d-e6fa82da21dd.png)

**Comment by XavierCai1996** [comment]
大概率是您没有合适的网络环境连接至`leetcode.com`，尝试在扩展的设置里切换`Source`这一项至`leetcode-cn.com`或者`Local`

**Comment by XiaoJiNu** [comment]
@XavierCai1996 谢谢，已经切换到了leetcode-cn.com，应该是我的vpn出了问题

**Comment by XavierCai1996** [comment]
@XiaoJiNu 不客气，感谢使用
