### ISSUE TITLE
cannot open source file "leetcode-definition.h"

### ISSUE THREAD

**Issue by XiaoJiNu** [XavierCai1996/vscode-leetcode-cpp-debug#5]
您好，现在无法导入这个库，如下图
![图片](https://user-images.githubusercontent.com/30587645/81815329-6b6c2200-955c-11ea-95c7-269219c14561.png)
我是在wsl系统下用的vscode，我不知道inclue path到底该设置为什么，我看网上有说是"/usr/include"路径，但是我没有找到这个路径。
如下图，我wsl系统打开目录就如下图，我只找到了googletest里面的路径
![图片](https://user-images.githubusercontent.com/30587645/81815751-f816e000-955c-11ea-9e2f-af00c055975f.png)

请问该怎么解决？谢谢。如果方便的话能否加您微信或者qq

**Comment by XavierCai1996** [comment]
目前看起来这并不是您的设置问题，而是插件未能支持WSL下的文件路径。

您可以将您的QQ或微信发送至[我的邮箱](mailto:cxw39@foxmail.com)，由我来添加您。

**Comment by XavierCai1996** [comment]
经过测试，WSL目前支持良好，没有明显问题
