### ISSUE TITLE
Error: Can not open the input file.

### ISSUE THREAD

**Issue by AndrewJoe15** [XavierCai1996/vscode-leetcode-cpp-debug#7]
Hi XavierCai，

我按照文档加了这两行代码，也建了一个test_case.txt文件，
#define INPUT "test_case.txt" // single-input
#define OUTPUT cout, "output.txt" // multi-output

debug时产生了一个错误：Error: Can not open the input file.

**Comment by XavierCai1996** [comment]
无法打开文件，很大概率是路径问题，例如：
1. 如果你没有修改过launch.json中的路径配置，检查.vscode目录所在位置（也就是你运行debugging的起始目录），是否与你的test_case.txt在同一目录
2. 如果你修改了launch.json中的路径配置，请依照配置检查路径
3. 如果你使用Code Runner插件运行，则需要保证test_case.txt与代码源文件在同一路径

如果你对检查路径是否正确没有把握，也可以尝试将文件分别放在.vscode所在目录和源码所在目录，通常路径不会被配置在其他位置。

如果仍有问题，欢迎继续留言讨论~

**Comment by AndrewJoe15** [comment]
Hi Xavier,
感谢回复。
如你所说，确实是路径问题。我把test_case.txt放到与.vscode同目录中，可以读取了。
但运行程序后，生成的output.txt里面什么都没有。
这是因为目前还不支持多个输入吗，test_case.txt有两行内容。

**Comment by XavierCai1996** [comment]
可以支持，但需要保证文件最后一行为空行（标记输入结束），这个目前应该算是bug。

**Comment by AndrewJoe15** [comment]
> 可以支持，但需要保证文件最后一行为空行（标记输入结束），这个目前应该算是bug。

原来如此。现在可以了。
感谢！

**Comment by XavierCai1996** [comment]
另外，昨天已经更新了一版修复了这个问题，也给`Error: Can not open the input file.`这个错误加了详细路径提示。

有别的问题也欢迎留言。
